# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Database-Team11' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Database-Team11
pod 'SnapKit', '~> 5.6.0'
pod 'Then'
pod 'Alamofire'

end
